import { X } from 'lucide-react'
import type { AiUsageLog } from '@/services/aiUsage'
import { formatScene, formatStatus, getSceneDefinition } from '../aiUsageLabels'

export default function AiUsageDetailDrawer({ detail, onClose }: { detail: { log: AiUsageLog; trace: AiUsageLog[] } | null; onClose: () => void }) {
  if (!detail) return null
  const { log, trace } = detail
  const sceneDefinition = getSceneDefinition(log.scene)
  return <div className="fixed inset-0 z-50 flex justify-end bg-black/20" role="dialog" aria-label="AI 调用日志详情"><button type="button" className="absolute inset-0 cursor-default" aria-label="关闭详情" onClick={onClose} /><aside className="relative h-full w-full max-w-[520px] overflow-y-auto bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><div className="text-xs font-medium uppercase tracking-[0.16em] text-[#167a6e]">AI Call Detail</div><h2 className="mt-1 text-xl font-semibold text-[#243447]">调用日志详情</h2></div><button type="button" onClick={onClose} className="rounded-lg p-2 text-[#78938d] hover:bg-[#f1faf8]"><X className="h-4 w-4" /></button></div><div className="mt-5 grid grid-cols-2 gap-3 text-xs">{[['用户', log.user_name || '未知用户'], ['场景', formatScene(log.scene)], ['模型', `${log.model_name || '未指定模型'}（${log.provider_name || '服务商未知'}）`], ['Key', log.key_masked || '—'], ['Token', `${(log.total_tokens ?? 0).toLocaleString()} (${log.token_source})`], ['成本', log.estimated_cost == null ? '未配置价格' : `${log.currency} ${log.estimated_cost.toFixed(6)}`], ['状态', formatStatus(log.status)], ['延迟', `${log.latency_ms ?? 0} ms`]].map(([label, value]) => <div key={label} className="rounded-xl bg-[#f7faf9] p-3"><div className="text-[#9ab1ab]">{label}</div><div className="mt-1 break-all font-medium text-[#34534d]">{value}</div>{label === '场景' && <div className="mt-1 text-[10px] text-[#9ab1ab]">{sceneDefinition.description}</div>}</div>)}</div><div className="mt-6"><h3 className="text-sm font-semibold text-[#243447]">请求链路</h3><p className="mt-1 break-all text-xs text-[#78938d]">trace: {log.trace_id}</p><div className="mt-3 space-y-2">{trace.map(item => <div key={item.id} className="rounded-xl border border-[#e5efeb] p-3 text-xs"><div className="flex justify-between"><span className="font-medium text-[#34534d]">Attempt {item.attempt_no}</span><span className="text-[#78938d]">{formatStatus(item.status)}</span></div><div className="mt-2 text-[#78938d]">输入 {item.input_tokens ?? '—'} · 输出 {item.output_tokens ?? '—'} · {item.latency_ms ?? '—'} ms</div></div>)}</div></div>{(log.prompt_content || log.response_content || log.error_message) && <div className="mt-6 space-y-4"><h3 className="text-sm font-semibold text-[#243447]">脱敏内容</h3>{log.prompt_content && <div><div className="mb-1 text-xs text-[#9ab1ab]">Prompt</div><pre className="max-h-40 overflow-auto whitespace-pre-wrap rounded-xl bg-[#f7faf9] p-3 text-xs text-[#56716b]">{log.prompt_content}</pre></div>}{log.response_content && <div><div className="mb-1 text-xs text-[#9ab1ab]">Response</div><pre className="max-h-40 overflow-auto whitespace-pre-wrap rounded-xl bg-[#f7faf9] p-3 text-xs text-[#56716b]">{log.response_content}</pre></div>}{log.error_message && <div className="rounded-xl bg-[#fff5f2] p-3 text-xs text-[#b25548]">{log.error_message}</div>}</div>}</aside></div>
}
