ARG BASE_REGISTRY=docker.io
FROM ${BASE_REGISTRY}/library/nginx:1.25-alpine

RUN rm -rf /etc/nginx/conf.d/default.conf

COPY ./NoteFlow_frontend/deploy/default.conf /etc/nginx/conf.d/default.conf
COPY ./NoteFlow_frontend/dist /usr/share/nginx/html
